### ISSUE TITLE
problem with raw data log

### ISSUE THREAD

**Issue by ks00x** [webspiderteam/Bluetooth-DMM-For-Windows#12]
When the raw data log option is on and the log file is sufficiantly large, the software does not connect properly anymore. There is no error message but the display shows nothing and the chart does not start. Deleting the log file and restarting helps. Maybe its better to clear the log file on start and/or make the raw data option off by default. Thanks for creating the App!!!

**Comment by webspiderteam** [comment]
To disable Lograwdata default is better I think. I made it enabled because when a new user had issues they won't think to enable it. Also I can make it daily that shouldn't be a problem I think

**Comment by webspiderteam** [comment]
done :)
