### ISSUE TITLE
file export mode

### ISSUE THREAD

**Issue by ks00x** [webspiderteam/Bluetooth-DMM-For-Windows#13]
I think it will be better to have 'csv' as the default for exporting the data. Maybe add a column for the full values in exponential format (without the u,m,k,M... prefixes).

**Comment by webspiderteam** [comment]
I will add an option to settings to make it default output.

> Maybe add a column for the full values in exponential format (without the u,m,k,M... prefixes).

Can you give an example

**Comment by ks00x** [comment]
> Can you give an example
now:
49,DC,-0.23,mV
new column (in V in this case):
49,DC,-0.23,mV,-2.3E-4

**Comment by webspiderteam** [comment]
I got it. You mean 1.23mV = 0.00123 V and 1Mohm as 1000000ohm. Right?

**Comment by ks00x** [comment]
> I got it. You mean 1.23mV = 0.00123 V and 1Mohm as 1000000ohm. Right?

yes, makes sense on an autorange meter to me.

**Comment by ludwich66** [comment]
Das Thema mit CSV ist die gleiche Baustelle wie im MQTT-Stream. Problem erkannt - Problem gesperrt!
Problem erkannt - Problem gebannt!
;-) ludwich

**Comment by webspiderteam** [comment]
done :) new release uploaded

**Comment by ludwich66** [comment]
High time to keep an eye on you (nearly tomorrow)
Thank you for the time invested, my wishes have not turned out to be entirely impractical ;-)
