### ISSUE TITLE
Review 115

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth-DMM-For-Windows#14]
(issue 115-1) Refresh MQTT string
A: Set to °F -->> Value 77
B: Change to Diodemode
Issue: ValueF is filled with Value from last measurement
{"Time":"02.08.2022 22:29:19","Device":"DMM_V05B","ValueS":" .0L ","ValueF":77,"Range":"V","Current":"","Symbols":"BUZZ,DIODE"}

(issue 115-2) JSON Error in Farad mode
--> ValueF with komma as separator "." needed?
"{ "Time":"02.08.2022 22:39:01", "Device":"DMM_V05B", "ValueS":"0.020", "ValueF":0,02, "Range":"nF", "Current":"", "Symbols":"" }"

(issue 115-3) if you not select a devicename in "Manage Devices"  and klick "Change Device Name"-Button, App shut down without error etc.

**Comment by webspiderteam** [comment]
thats what I said. tomorrow I will lookup

**Comment by ludwich66** [comment]
good night today

**Comment by ludwich66** [comment]
hi engin,
which iconsets do you use?
Please tell me best size and format for icons

ludwich

**Comment by webspiderteam** [comment]
> Refresh MQTT string

I think I should change ValueF as null when not numerical. thats the best way to handle.

for which icons? App icon? Graph popup? Menu? Flags? Device Selector? Main Display?

**Comment by webspiderteam** [comment]
most of them is svg format so resizeable only images that I used is here
https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/tree/master/BluetoothDMM%20WPF/BluetoothDMM/Assets

**Comment by ludwich66** [comment]
Draft icons for BT-DMM
interested right?

[BT-DMM_ICON-SET.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9251215/BT-DMM_ICON-SET.zip)

**Comment by ludwich66** [comment]
View on Top2
![BT-DMM_VIEW_ONTOP2](https://user-images.githubusercontent.com/12202733/182618086-2772e07d-4250-4fd1-b994-d81c59823560.svg)

**Comment by webspiderteam** [comment]
![image](https://user-images.githubusercontent.com/85828505/182626503-ee5fda92-4343-4424-ad4e-dfc750b6432d.png)
what do you think?

**Comment by ludwich66** [comment]
more wishes?
![image](https://user-images.githubusercontent.com/12202733/182627950-15f62ca1-0631-4a54-9b80-7185dd1429fb.png)

**Comment by ludwich66** [comment]
last-complete-set

[BT-DMM-ICONSET2.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9252050/BT-DMM-ICONSET2.zip)

**Comment by ludwich66** [comment]
> ![image](https://user-images.githubusercontent.com/85828505/182626503-ee5fda92-4343-4424-ad4e-dfc750b6432d.png)
> what do you think?

Yes looks good ;-)

Is it possible to move your Setting-Wheel from right to the left menu entries 
AND
bring language setting (or button to open subpage ) in first order of basic MENU?

... and you need a Copyright Legal Info

But that's Eye- and Ergonomic-Candys - Base functions must have Priority.


You are a great developer !


Did you know my nikname at my job?
"merciless ruler"

;-) ludwich

  | occupation |  
-- | -- | --


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

ludwich
