### ISSUE TITLE
CSV Export 

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth-DMM-For-Windows#19]
MQTT an Display is OK
CSV-Export Missing column heading 
value without decimal sign
It was an old AAA Cell with 1,363 V DC
![image](https://user-images.githubusercontent.com/12202733/183461630-4af19848-af81-4586-8741-69048cde7c81.png)

Ludwich

**Comment by webspiderteam** [comment]
Done :) and Published with new release ;)
