### ISSUE TITLE
Review 1.17

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth-DMM-For-Windows#21]
where is a good place to store the iconset?
[BT-DMM-ICONSET.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9270578/BT-DMM-ICONSET.zip)
![image](https://user-images.githubusercontent.com/12202733/183128864-61bf4e8b-ceff-4aca-a137-138bd8aaf0e4.png)

_Originally posted by @ludwich66 in https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/discussions/17#discussioncomment-3335616_

**Comment by webspiderteam** [comment]
O already uploaded in extra folder

**Comment by ludwich66** [comment]
> O already uploaded in extra folder

now i seen it ;-)
