### ISSUE TITLE
Polish translate

### ISSUE THREAD

**Issue by kris0725pl** [webspiderteam/Bluetooth-DMM-For-Windows#32]
Hi...can u change TrueRMS to TrueRMS? Translate in polish is terrible :)
![truerms](https://user-images.githubusercontent.com/70975595/203324349-f4c33d8a-2329-47f8-bdc7-64a155668ada.jpg)

For me...better is in folder files in .txt or something else to edit language :)

In line 78:
TrueRMS,PRAWDZIWE RMS
TrueRMS,True RMS

**Comment by ludwich66** [comment]
Have you "checked" the complete Resources.pl.resx.csv file? - Of course, that's all machine-translated - it's always possible to do better ;-)

What remote options can you set for the 207 with the original software?

Ludwich

**Comment by webspiderteam** [comment]
Done :) 
[pl.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/10069866/pl.zip)

**Comment by webspiderteam** [comment]
> Translate in polish is terrible :)

I know but I dont know polish :) I can only translate with google translate by myself and thats the result :)

**Comment by webspiderteam** [comment]
English is enough for me 😇

**Comment by kris0725pl** [comment]
Ok, thx. I try tommorow new translate ;)

**Comment by kris0725pl** [comment]
![;k](https://user-images.githubusercontent.com/70975595/203571180-522ffa04-6a08-43fa-9a1e-ef50725ce9fa.jpg)
ok..looks better :)

**Comment by ludwich66** [comment]
> ![;k](https://user-images.githubusercontent.com/70975595/203571180-522ffa04-6a08-43fa-9a1e-ef50725ce9fa.jpg)
> ok..looks better :)

Have you looked at the remote settings from the software, it would be nice if you could say something about that

 Czy przejrzałeś ustawienia pilota z poziomu oprogramowania, byłoby miło, gdybyś mógł coś o tym powiedzieć
-Google Translate-
Ł

L

**Comment by kris0725pl** [comment]
What remote?

**Comment by ludwich66** [comment]
> What remote?

https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/wiki#remote-features

![71px0w](https://user-images.githubusercontent.com/12202733/203297049-c29c395d-e707-48c1-ba53-bf18c99da46c.gif)

**Comment by kris0725pl** [comment]
Yes...not working properly. From auto to diode when click button...works. when i press ncv...buttons frozen. No response from application. Only fix is press on multimeter hz button to back auto mode. I show everything on my video on youtube.

**Comment by webspiderteam** [comment]
> Yes...not working properly. From auto to diode when click button...works. when i press ncv...buttons frozen. No response from application. Only fix is press on multimeter hz button to back auto mode. I show everything on my video on youtube.
> 
> And...this buttons are not visible in OBS.
> 
> Cant move this buttons....

I think Hz mode only works when probes not connected. But yes you are right NCV mode blocks other functions but it's not related with app. Multimeters NCV system not releasing other functions. Maybe there is another function to release NCV MODE. On the other hand there was only one HOLD data and I really not sure if it's working or not cause my 9002 not accept any of commands so I couldn't test them by myself. I wish I had one of them to test them but I haven't and also I can't buy either it's price is too high for our country circumstances.

**Comment by ludwich66** [comment]
Hi Engin,
**"I think Hz mode only works when probes not connected"**
The Hz function only works through the probes.
With open probes it's like a radio - it picks up something.
It works perfectly on the V05B.

What codes do you currently have?
See my list in other Threat.

Ludwich

**Comment by webspiderteam** [comment]
> The Hz function only works through the probes.

on ST207 when he changes modes manually over multimeter hz not shows up with probes or Do I missed?



> What codes do you currently have?

ea ec 70 ed a2 c1 32 71 64 99 for auto
ea ec 70 e3 a2 c1 32 71 64 9b C Deg
ea ec 70 e2 a2 c1 32 71 64 98 F Deg
ea ec 70 e5 a2 c1 32 71 64 81 Cap
ea ec 70 e4 a2 c1 32 71 64 86 Diode
ea ec 70 e7 a2 c1 32 71 64 87 NCV
ea ec 70 e6 a2 c1 32 71 64 84 Hz
ea ec 70 91 a2 c1 32 71 64 95 Hold
ea ec 70 84 a2 c1 32 71 64 e6 Min/max
ea ec 70 93 a2 c1 32 71 64 eb Not known

**Comment by kris0725pl** [comment]
Hi..you add battery indicator? Looks nice :)
