### ISSUE TITLE
Review 1.12

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth-DMM-For-Windows#7]
Hi Engin ( ok for you?)

where can i best change translation files. is it saved as .dll?

+++
Please ad Polish for krystof ;-)

ludwich

**Comment by webspiderteam** [comment]
I already added Polish and sended :) 

you need german translation I think
[de.csv](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9189095/de.csv)
[en.csv](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9189097/en.csv)
here in csv format you can edit and send me back then I can compile as dll

**Comment by ludwich66** [comment]
Hi Engin ,
first "Almanca"

"not connected" is first not translated - changes after established connection

Translation first try - check space or cuted literals in second step
[de.csv](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9189419/de.csv)

+++

Ludwich

**Comment by webspiderteam** [comment]
[de.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9189985/de.zip)
copy files inside zip and paste to app folder

**Comment by webspiderteam** [comment]
> "not connected" is first not translated - changes after established connection

I know I fixed it but not published yet

> Translation first try - check space or cuted literals in second step

I saw it in device management and connection popup 
I fixed connection poppup and trying find a way to fix in device manegement

**Comment by webspiderteam** [comment]
> * ist there a option to read "localisation" from windows and use this info as preselection?

already done :) but I dont know published release has it or not

**Comment by webspiderteam** [comment]
[Release.zip](https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/files/9190282/Release.zip)
posibly this has all you want :)

**Comment by ludwich66** [comment]
Is Version 1.12 on Relaespage actually now?
I sent messages to Youtube Users with the wish to help Translate an check.
Please actualize it soon. 

Ludwich

**Comment by webspiderteam** [comment]
not this one but close enough I can upload a new release too

**Comment by ludwich66** [comment]
+++ Please 👍 +++

**Comment by webspiderteam** [comment]
do you think this is 1.13? or just 1.12a?

**Comment by webspiderteam** [comment]
1.13 Released :)
